# Generated by Django 5.1.7 on 2025-03-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_connectionparameter_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionparameter',
            name='database',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
